services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: sh -c "pnpm run migrate && pnpm prisma generate && pnpm run start:dev orders"
    depends_on:
      - postgres-db
    env_file:
      - ./apps/orders/.env
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: ./apps/orders/src
          target: /usr/src/app/apps/orders/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./apps/orders/prisma/migrations
        - action: rebuild
          path: ./package.json

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm run migrate && pnpm prisma generate && pnpm run start:dev auth"
    depends_on:
      - postgres-db
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    develop:
      watch:
        - action: sync
          path: ./apps/auth/src
          target: /usr/src/app/apps/auth/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./apps/auth/prisma/migrations
        - action: rebuild
          path: ./package.json

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3004:3004'
    develop:
      watch:
        - action: sync
          path: ./apps/payments/src
          target: /usr/src/app/apps/payments/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./package.json

  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: sh -c "pnpm run migrate && pnpm prisma generate && pnpm run start:dev products"
    depends_on:
      - postgres-db
    env_file:
      - ./apps/products/.env
    ports:
      - '3002:3002'
    develop:
      watch:
        - action: sync
          path: ./apps/products/src
          target: /usr/src/app/apps/products/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./apps/products/prisma/migrations
        - action: rebuild
          path: ./package.json

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    develop:
      watch:
        - action: sync
          path: ./apps/notifications/src
          target: /usr/src/app/apps/notifications/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./package.json

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3003:3003'
    develop:
      watch:
        - action: sync
          path: ./apps/gateway/src
          target: /usr/src/app/apps/gateway/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./package.json

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  db-data:
  # auth-db-data:
  # products-db-data:
