services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: sh -c "pnpm run migrate && pnpm prisma generate && pnpm run start:dev orders"
    depends_on:
      - orders-db
    env_file:
      - ./apps/orders/.env
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: ./apps/orders/src
          target: /usr/src/app/apps/orders/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./apps/orders/prisma/migrations
        - action: rebuild
          path: ./package.json

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm run migrate && pnpm prisma generate && pnpm run start:dev auth"
    depends_on:
      - auth-db
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    develop:
      watch:
        - action: sync
          path: ./apps/auth/src
          target: /usr/src/app/apps/auth/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./apps/auth/prisma/migrations
        - action: rebuild
          path: ./package.json

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    develop:
      watch:
        - action: sync
          path: ./apps/payments/src
          target: /usr/src/app/apps/payments/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./package.json

  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: sh -c "pnpm run migrate && pnpm prisma generate && pnpm run start:dev products"
    depends_on:
      - products-db
    env_file:
      - ./apps/products/.env
    ports:
      - '3004:3004'
    develop:
      watch:
        - action: sync
          path: ./apps/products/src
          target: /usr/src/app/apps/products/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./apps/products/prisma/migrations
        - action: rebuild
          path: ./package.json

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    develop:
      watch:
        - action: sync
          path: ./apps/notifications/src
          target: /usr/src/app/apps/notifications/src
        - action: sync
          path: ./libs/common/src
          target: /usr/src/app/libs/common/src
        - action: rebuild
          path: ./package.json

  orders-db:
    image: postgres:17
    container_name: orders-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders
    ports:
      - 5432:5432
    volumes:
      - orders-db-data:/var/lib/postgresql/data

  auth-db:
    image: postgres:17
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - 5433:5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  products-db:
    image: postgres:17
    container_name: products-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=products
    ports:
      - 5434:5432
    volumes:
      - products-db-data:/var/lib/postgresql/data

volumes:
  orders-db-data:
  auth-db-data:
  products-db-data:
